name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    CI:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.21

            - name: Install dependencies
              run: cd server && go mod download

            - name: Run tests
              run: cd server && go test -v
